services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coonspect_api
    restart: always
    ports:
      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - coonspect_network

  mongodb:
    image: mongo:latest
    container_name: coonspect_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - coonspect_network

networks:
  coonspect_network:
    driver: bridge

volumes:
  mongodb_data: