services:
  backend:
    build: ./backend
    container_name: coonspect_api
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_INTERNAL_PORT}
    ports:
      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - mongodb
      - redis
    networks:
      - coonspect_network

  worker:
    build: ./backend
    container_name: coonspect_worker
    command: taskiq worker app.tasks.lecture:broker
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - mongodb
      - redis
    networks:
      - coonspect_network

  mongodb:
    image: mongo:latest
    container_name: coonspect_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "${MONGO_PORT_EXTERNAL}:${MONGO_PORT_INTERNAL}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - coonspect_network

  redis:
    image: redis:7-alpine
    container_name: coonspect_redis
    ports:
      - "${REDIS_PORT_EXTERNAL}:${REDIS_PORT_INTERNAL}"
    networks:
      - coonspect_network

networks:
  coonspect_network:
    driver: bridge

volumes:
  mongodb_data: