[project]
name = "cs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.129.0",
    "motor>=3.7.1",
    "pydantic-settings>=2.13.0",
    "uvicorn[standard]>=0.40.0",
]
